#pragma once
#ifndef __ENUM_H__
#define __ENUM_H__

enum RACE { RACE_PLAYER, RACE_WRIATH, RACE_DEVIL, RACE_SKELETON, RACE_DIABLO, RACE_END };
enum DIRECTION { DIRECTION_UP, DIRECTION_DOWN, DIRECTION_LEFT, DIRECTION_RIGHT, DIRECTION_END };
enum ATTACKTYPE { ATTACKTYPE_PEACE, ATTACKTYPE_AGRO, ATTACKTYPE_END };
enum MOVETYPE { MOVETYPE_FIX, MOVETYPE_ROAMING, MOVETYPE_END };
enum CHATTYPE { CHATTYPE_SAY, CHATTYPE_TELL, CHATTYPE_SHOUT, CHATTYPE_BOSS, CHATTYPE_END };

#endif // !__ENUM_H__
